### ISSUE TITLE
Build error on Ubuntu 16.04

### ISSUE THREAD

**Issue by Asgard1232** [CTSRD-CHERI/cheribuild#177] opened 2021-01-23 00:43 UTC
Cheribuild doesn't run the Riscv64 or Mips64 targets on Ubuntu 16.04 (installed from the file ubuntu-16.04.7-desktop-amd64.iso). The command line text is attached - apparently bmake can't compile (I wasn't running cheribuild as root).
[error.txt](https://github.com/CTSRD-CHERI/cheribuild/files/5859304/error.txt)

**Comment by jrtc27** [comment] 2021-01-23 18:56
I'm currently seeing if I can reproduce it in a fresh 16.04 chroot. Though we'll probably drop support for 16.04 once Canonical drop security support for it, which is due to happen in April, so I would suggest you look at upgrading to a later version regardless, both to continue being supported by us and (more importantly) to continue getting security support for your system.

**Comment by jrtc27** [comment] 2021-01-23 21:04
Fixed in https://github.com/CTSRD-CHERI/cheribsd/commit/d178833d5ba9f6af5dc6e11b97722948a484590a (you'll need to `git -C ~/cheri/cheribsd checkout dev` for now until we fast-forward master), though you'll run into another build issue unless you install clang-4.0 or above that I'm preparing a fix for.

**Closed by jrtc27** 2021-01-23 21:04 UTC

**Comment by jrtc27** [comment] 2021-01-23 23:02
Ok, if you apply https://github.com/CTSRD-CHERI/cheribsd/pull/907 and https://github.com/CTSRD-CHERI/cheribsd/pull/908 locally for now until merged to dev (or master) you should be able to build on Ubuntu 16.04.
