### ISSUE TITLE
makefs command fails because manifest file is missing entry

### ISSUE THREAD

**Issue by kgudka** [CTSRD-CHERI/cheribuild#11] opened 2016-08-05 15:19 UTC
When building a disk image, makefs complains that firstly, the METALOG manifest file is missing the /usr/tests folder and secondly about the entry ./usr/tests/cheri/lib/libc/tls/.debug/ which should be ./usr/tests/cheri/lib/libc/tls/.debug

**Comment by RichardsonAlex** [comment] 2016-08-11 01:35
Probably caused by something in CheriBSD changing. The script just assumes that whatever CheriBSD build creates is valid.
Does a clean build still have that issue? I'll look if I can reproduce it.

**Comment by arichardson** [comment] 2017-11-17 13:29
Fixed in CheriBSD

**Closed by arichardson** 2017-11-17 13:29 UTC
